package Livreur;


import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class PersonelEkran extends javax.swing.JDialog {

    
    static DefaultTableModel model;
    PersonelIslemleri islemler = new PersonelIslemleri();

    PersonelIslemleri.Ekle ekle = new PersonelIslemleri().new Ekle();


    
    
    /**
     * Creates new form hp
     */
    public PersonelEkran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel)Personel_tablosu.getModel();
        personelGoruntule();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Personel_tablosu = new javax.swing.JTable();
        Txt_ara = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lbl_mesaj = new javax.swing.JLabel();
        Btn_personelEkle = new javax.swing.JButton();
        Txt_ad = new javax.swing.JTextField();
        Txt_soyad = new javax.swing.JTextField();
        Txt_departman = new javax.swing.JTextField();
        Txt_maas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Btn_temizle = new javax.swing.JButton();
        Btn_personelGuncelle = new javax.swing.JButton();
        Btn_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(700, 300, 0, 0));

        Personel_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prénom", "Zone", "Salaire"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Personel_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Personel_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Personel_tablosu);
        if (Personel_tablosu.getColumnModel().getColumnCount() > 0) {
            Personel_tablosu.getColumnModel().getColumn(0).setResizable(false);
            Personel_tablosu.getColumnModel().getColumn(1).setResizable(false);
            Personel_tablosu.getColumnModel().getColumn(2).setResizable(false);
        }

        Txt_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_araActionPerformed(evt);
            }
        });
        Txt_ara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_araKeyReleased(evt);
            }
        });

        jLabel1.setText("Nom:");

        jLabel2.setText("Prénom:");

        jLabel3.setText("Zone:");

        jLabel4.setText("Salaire:");

        Btn_personelEkle.setText("Ajouter");
        Btn_personelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_personelEkleActionPerformed(evt);
            }
        });

        jLabel6.setText("Recherche");

        Btn_temizle.setText("Clear");
        Btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_temizleActionPerformed(evt);
            }
        });

        Btn_personelGuncelle.setText("Modifier ");
        Btn_personelGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_personelGuncelleActionPerformed(evt);
            }
        });

        Btn_sil.setText("Supprimer");
        Btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_ara))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel3))
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Txt_departman, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Txt_maas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(Btn_temizle)
                                                .addGap(128, 128, 128)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Btn_personelGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Btn_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_personelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jSeparator1))
                        .addGap(181, 181, 181)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Btn_personelGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_personelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_departman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_temizle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Lbl_mesaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_araActionPerformed

    
    
    private void Txt_araKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_araKeyReleased
        
        String ara;
        ara  = Txt_ara.getText();
        islemler.Ara(ara);

        
    }//GEN-LAST:event_Txt_araKeyReleased

    private void Btn_personelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_personelEkleActionPerformed
        Lbl_mesaj.setText("");
        if (Txt_ad.getText().equals("") || Txt_departman.getText().equals("")
                || Txt_soyad.getText().equals("") || Txt_maas.getText().equals("")){
        
            Lbl_mesaj.setText("Livreur n'est pas ajouter vueillez remplir tout les cases...");

        }
        else {

        String ad = Txt_ad.getText();
        String soyad = Txt_soyad.getText();
        String departman = Txt_departman.getText();
        String maas = Txt_maas.getText();

        ekle.personelEkle(ad, soyad, departman, maas);

        personelGoruntule();

        Lbl_mesaj.setText("Livreur ajouter...");
         
            
        }
        
        
        
    }//GEN-LAST:event_Btn_personelEkleActionPerformed

    private void Btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_temizleActionPerformed
        
        Txt_ad.setText("");
        Txt_soyad.setText("");
        Txt_departman.setText("");
        Txt_maas.setText("");
        Lbl_mesaj.setText("");
        Personel_tablosu.getSelectionModel().clearSelection();

    }//GEN-LAST:event_Btn_temizleActionPerformed

    private void Personel_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personel_tablosuMouseClicked
        
        int selectedrow = Personel_tablosu.getSelectedRow();
        
        Txt_ad.setText(model.getValueAt(selectedrow, 1).toString());
        Txt_soyad.setText(model.getValueAt(selectedrow, 2).toString());
        Txt_departman.setText(model.getValueAt(selectedrow, 3).toString());
        Txt_maas.setText(model.getValueAt(selectedrow, 4).toString());
        

    }//GEN-LAST:event_Personel_tablosuMouseClicked

    private void Btn_personelGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_personelGuncelleActionPerformed

        String ad = Txt_ad.getText();
        String soyad = Txt_soyad.getText();
        String departman = Txt_departman.getText();
        String maas = Txt_maas.getText();
         int selectedrow = Personel_tablosu.getSelectedRow();

         if (selectedrow == -1) {
         
             if (model.getRowCount() == 0) {
             
                 Lbl_mesaj.setText("Erreur Tableau vide!");
             
             }
             else {
             
                 Lbl_mesaj.setText("Merci de choisir une case pour modifier");
                 
             }
           
         }
         else {
         
             if (Txt_ad.getText().equals("") || Txt_departman.getText().equals("")
                || Txt_soyad.getText().equals("") || Txt_maas.getText().equals("")){

            Lbl_mesaj.setText("Erreur de modification veuillez remplir tous les cases...");
            
        }
        else{
             int id = (int)model.getValueAt(selectedrow, 0 );
             islemler.personelGuncelle(id,ad,soyad,departman,maas);

             personelGoruntule();
             Lbl_mesaj.setText("Livreur modifier.");
        }
         }
        
    }//GEN-LAST:event_Btn_personelGuncelleActionPerformed

    private void Btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_silActionPerformed
       
        Lbl_mesaj.setText("");
        int selectedrow = Personel_tablosu.getSelectedRow();
        if (selectedrow == -1) {

            if (model.getRowCount() == 0) {
            
                Lbl_mesaj.setText("Erreur tableau vide");
                
            }
            else {
            
                Lbl_mesaj.setText("Merci de choisir une case pour la suppression! ");
                
            }
            
        }
        else {

            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.personelSil(id);
            personelGoruntule();

            Lbl_mesaj.setText("Livreur supprimer");
            
        }
        
    }//GEN-LAST:event_Btn_silActionPerformed

    /**
     */
    
    public void personelGoruntule(){

        model.setRowCount(0);
        ArrayList<Personel> calisanlar = new ArrayList<Personel>();
        calisanlar = islemler.personelGetir();

        if(calisanlar != null) {
        
            for (Personel calisan : calisanlar){
                

                Object[] eklenecek = {calisan.getId(), calisan.getAd(), calisan.getSoyad(), calisan.getDepartman(), calisan.getMaas()};
                model.addRow(eklenecek);
            }
        }
        
    } 
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PersonelEkran dialog = new PersonelEkran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_personelEkle;
    private javax.swing.JButton Btn_personelGuncelle;
    private javax.swing.JButton Btn_sil;
    private javax.swing.JButton Btn_temizle;
    private javax.swing.JLabel Lbl_mesaj;
    public static javax.swing.JTable Personel_tablosu;
    private javax.swing.JTextField Txt_ad;
    private javax.swing.JTextField Txt_ara;
    private javax.swing.JTextField Txt_departman;
    private javax.swing.JTextField Txt_maas;
    private javax.swing.JTextField Txt_soyad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
